---
title: Open WebUI on OCI
description: >-
  Deploy upstream Open WebUI on OCI with OCI OpenAI-compatible endpoint
  configuration and optional accelerator assets.
schemaVersion: 1.1.0
version: "20260219"
locale: en

variableGroups:
  - title: Hidden
    visible: false
    variables:
      - tenancy_ocid
      - region

  - title: Core
    variables:
      - compartment_ocid
      - stack_prefix
      - ssh_public_key
      - availability_domain_number
      - image_ocid
      - instance_shape
      - instance_ocpus
      - instance_memory_in_gbs
      - boot_volume_size_gbs

  - title: Network
    variables:
      - vcn_cidr_block
      - public_subnet_cidr_block
      - allow_ssh_cidr
      - allow_web_cidr
      - web_port

  - title: Open WebUI Runtime
    variables:
      - open_webui_version
      - openai_api_base_url
      - openai_api_key
      - default_models
      - webui_secret_key

  - title: OCI Accelerator Compatibility
    variables:
      - enable_oci_accelerator
      - accelerator_repo_url
      - accelerator_ref
      - oci_compartment_ocid_override
      - oci_region_override

  - title: IAM (Optional)
    variables:
      - create_iam_resources
      - dynamic_group_name
      - policy_name

variables:
  tenancy_ocid:
    type: string
    required: true
    visible: false

  region:
    type: oci:identity:region:name
    required: true
    visible: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Deployment Compartment
    default: compartment_ocid

  stack_prefix:
    type: string
    required: true
    default: openwebui
    title: Resource Prefix

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: SSH Public Key

  availability_domain_number:
    type: integer
    required: true
    default: 1
    title: Availability Domain Number

  image_ocid:
    type: string
    required: false
    default: ""
    title: Custom Image OCID (Optional)

  instance_shape:
    type: string
    required: true
    default: VM.Standard.E4.Flex
    title: Compute Shape

  instance_ocpus:
    type: integer
    required: true
    default: 1
    title: Flex OCPUs

  instance_memory_in_gbs:
    type: integer
    required: true
    default: 8
    title: Flex Memory (GB)

  boot_volume_size_gbs:
    type: integer
    required: true
    default: 80
    title: Boot Volume Size (GB)

  vcn_cidr_block:
    type: string
    required: true
    default: 10.46.0.0/16
    title: VCN CIDR

  public_subnet_cidr_block:
    type: string
    required: true
    default: 10.46.0.0/24
    title: Public Subnet CIDR

  allow_ssh_cidr:
    type: string
    required: true
    default: 0.0.0.0/0
    title: Allowed SSH CIDR

  allow_web_cidr:
    type: string
    required: true
    default: 0.0.0.0/0
    title: Allowed Web CIDR

  web_port:
    type: integer
    required: true
    default: 3000
    title: Open WebUI Port

  open_webui_version:
    type: string
    required: true
    default: v0.8.3
    title: Open WebUI Image Tag

  openai_api_base_url:
    type: string
    required: false
    default: ""
    title: OpenAI-Compatible Endpoint URL

  openai_api_key:
    type: password
    required: false
    default: ""
    title: OpenAI-Compatible API Key

  default_models:
    type: string
    required: false
    default: ""
    title: Default Model IDs

  webui_secret_key:
    type: password
    required: false
    default: ""
    title: WebUI Secret Key (Optional)

  enable_oci_accelerator:
    type: boolean
    required: true
    default: true
    title: Enable OCI Accelerator Assets

  accelerator_repo_url:
    type: string
    required: true
    default: https://github.com/oci-ai-architects/oci_open-webui.git
    title: Accelerator Repository URL

  accelerator_ref:
    type: string
    required: true
    default: main
    title: Accelerator Branch or Tag

  oci_compartment_ocid_override:
    type: string
    required: false
    default: ""
    title: Runtime OCI Compartment Override

  oci_region_override:
    type: string
    required: false
    default: ""
    title: Runtime OCI Region Override

  create_iam_resources:
    type: boolean
    required: true
    default: false
    title: Create IAM Dynamic Group and Policy

  dynamic_group_name:
    type: string
    required: true
    default: openwebui-instances
    title: Dynamic Group Name

  policy_name:
    type: string
    required: true
    default: openwebui-genai-policy
    title: IAM Policy Name
